# Generated by Django 4.0.3 on 2022-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Модель комплектующего')),
                ('energy_rate', models.FloatField(max_length=200, verbose_name='Расход за час в киловаттах')),
                ('income', models.FloatField(max_length=200, verbose_name='Доход за час в долларах')),
                ('device_amount', models.IntegerField(max_length=15, verbose_name='Кол. устройств')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
