# Generated by Django 4.0.3 on 2022-03-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_amount',
        ),
    ]
