# Generated by Django 4.0.3 on 2022-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_energy_rate_alter_device_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='income1',
            field=models.FloatField(default=1, max_length=300, verbose_name='Доход за час в долларах'),
            preserve_default=False,
        ),
    ]
