# Generated by Django 4.0.3 on 2022-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_income1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Модель комплектующего')),
                ('energy_rate', models.FloatField(max_length=300, verbose_name='Расход за час в киловаттах')),
                ('income', models.FloatField(max_length=300, verbose_name='Доход за час в долларах')),
                ('income1', models.FloatField(max_length=300, verbose_name='Доход за час в долларах')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
