# Generated by Django 4.0.3 on 2022-03-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_devicemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceModel',
        ),
    ]
