# Generated by Django 4.0.3 on 2022-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_devicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='income1',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name='Тип устройства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='energy_rate',
            field=models.FloatField(max_length=200, verbose_name='Расход за час в киловаттах'),
        ),
        migrations.AlterField(
            model_name='device',
            name='income',
            field=models.FloatField(max_length=200, verbose_name='Доход за час в долларах'),
        ),
    ]
