# Generated by Django 4.0.3 on 2022-03-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_device_income1_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
    ]
